### ISSUE TITLE
Your the idiot

### ISSUE THREAD

**Issue by dschaf** [xoElf/ZenoniteCleaner#2]
Sense u wanted to be a idiot and call me stupid in my first issue I opened first off I know it’s a batch second I asked how to make it u just don’t pop the cleaner out of your ass I was asking how to MAKE meaning how to get ban traces for the cleaner this was so long ago too lmao I’ve been had my own cleaner Keep thinking your “smart” retard and the part that makes you looking even more idiotic is you thinking I asked how to make a bat file…

**Comment by xoElf** [comment]
I had a stroke trying to read this. Use periods and commas. Correct your grammar before you call me an idiot. 
"I’ve been had my own cleaner"
"Sense u wanted to be a idiot"
Your argument is invalid because you don't know how to use proper spelling and grammar.
